services:
  - type: web
    name: qbids
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: NPM_CONFIG_PRODUCTION
        value: false
